kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: hello-world-node-js-git
  namespace: cc-uc-1-voyaging-coders
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/cc-uc-1-voyaging-coders/buildconfigs/hello-world-node-js-git
  uid: effda2dd-169f-4320-bdad-e7f3e6516734
  resourceVersion: '7591203'
  creationTimestamp: '2020-05-10T02:48:01Z'
  labels:
    app: hello-world-node-js-git
    app.kubernetes.io/component: hello-world-node-js-git
    app.kubernetes.io/instance: hello-world-node-js-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: hello-world-node-js-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 10-SCL
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/chait2k3/HelloWorldNodeJS.git'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-world-node-js-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:10-SCL'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/chait2k3/HelloWorldNodeJS.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: hello-world-node-js-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: hello-world-node-js-git-github-webhook-secret
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:85f7df07bd2f71aea40b01f91e06377dc12020ac4be63ad9296b4ce7cf2f4ee4
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 1
