kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/chait2k3/HelloWorldNodeJS.git'
  selfLink: >-
    /apis/image.openshift.io/v1/namespaces/cc-uc-1-voyaging-coders/imagestreams/hello-world-node-js-git
  resourceVersion: '7591191'
  name: hello-world-node-js-git
  uid: 6ccdd477-7418-47f4-a249-7fea3eb59b8d
  creationTimestamp: '2020-05-10T02:48:01Z'
  generation: 1
  namespace: cc-uc-1-voyaging-coders
  labels:
    app: hello-world-node-js-git
    app.kubernetes.io/component: hello-world-node-js-git
    app.kubernetes.io/instance: hello-world-node-js-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: hello-world-node-js-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 10-SCL
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: >-
    image-registry.openshift-image-registry.svc:5000/cc-uc-1-voyaging-coders/hello-world-node-js-git
