kind: ReplicationController
apiVersion: v1
metadata:
  annotations:
    openshift.io/deployment-config.name: helloworldnj
    openshift.io/deployer-pod.completed-at: '2020-05-12 05:25:20 +0000 UTC'
    openshift.io/deployment.phase: Complete
    openshift.io/deployer-pod.created-at: '2020-05-12 05:25:02 +0000 UTC'
    openshift.io/deployment-config.latest-version: '4'
    openshift.io/deployment.status-reason: config change
    openshift.io/deployment.replicas: '1'
    openshift.io/encoded-deployment-config: >
      {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"helloworldnj","namespace":"cc-uc-1-voyaging-coders","selfLink":"/apis/apps.openshift.io/v1/namespaces/cc-uc-1-voyaging-coders/deploymentconfigs/helloworldnj","uid":"c48a79b1-0b8e-4b7d-8f8d-89d9e8a1bc1f","resourceVersion":"8560581","generation":6,"creationTimestamp":"2020-05-12T02:46:08Z","labels":{"app":"helloworldnj","app.kubernetes.io/component":"helloworldnj","app.kubernetes.io/instance":"helloworldnj"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{"limits":{"cpu":"200m","memory":"300Mi"},"requests":{"cpu":"100m","memory":"200Mi"}},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["helloworldnj"],"from":{"kind":"ImageStreamTag","namespace":"cc-uc-1-voyaging-coders","name":"helloworldnj:v1"},"lastTriggeredImage":"docker.io/chait2k3/helloworldnj@sha256:afb6f9d2906c790ea4fb954f48b4a5d60e87b78f52905eccd7166fb54a138b5c"}},{"type":"ConfigChange"}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"helloworldnj","deploymentconfig":"helloworldnj"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"helloworldnj","deploymentconfig":"helloworldnj"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"containers":[{"name":"helloworldnj","image":"docker.io/chait2k3/helloworldnj@sha256:afb6f9d2906c790ea4fb954f48b4a5d60e87b78f52905eccd7166fb54a138b5c","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{"limits":{"cpu":"200m","memory":"300Mi"},"requests":{"cpu":"100m","memory":"200Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":4,"observedGeneration":6,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config
      change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Progressing","status":"False","lastUpdateTime":"2020-05-12T05:17:04Z","lastTransitionTime":"2020-05-12T05:17:04Z","reason":"ProgressDeadlineExceeded","message":"replication
      controller \"helloworldnj-4\" has failed
      progressing"},{"type":"Available","status":"False","lastUpdateTime":"2020-05-12T05:23:51Z","lastTransitionTime":"2020-05-12T05:23:51Z","message":"Deployment
      config does not have minimum availability."}]}}
    openshift.io/deployer-pod.name: helloworldnj-4-deploy
  selfLink: >-
    /api/v1/namespaces/cc-uc-1-voyaging-coders/replicationcontrollers/helloworldnj-4
  resourceVersion: '8560955'
  name: helloworldnj-4
  uid: ec3ea31e-7af2-499d-88de-d5e47c75037e
  creationTimestamp: '2020-05-12T05:25:01Z'
  generation: 2
  namespace: cc-uc-1-voyaging-coders
  ownerReferences:
    - apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: helloworldnj
      uid: c48a79b1-0b8e-4b7d-8f8d-89d9e8a1bc1f
      controller: true
      blockOwnerDeletion: true
  labels:
    app: helloworldnj
    app.kubernetes.io/component: helloworldnj
    app.kubernetes.io/instance: helloworldnj
    openshift.io/deployment-config.name: helloworldnj
spec:
  replicas: 1
  selector:
    app: helloworldnj
    deployment: helloworldnj-4
    deploymentconfig: helloworldnj
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworldnj
        deployment: helloworldnj-4
        deploymentconfig: helloworldnj
      annotations:
        openshift.io/deployment-config.latest-version: '4'
        openshift.io/deployment-config.name: helloworldnj
        openshift.io/deployment.name: helloworldnj-4
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: helloworldnj
          image: >-
            docker.io/chait2k3/helloworldnj@sha256:afb6f9d2906c790ea4fb954f48b4a5d60e87b78f52905eccd7166fb54a138b5c
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  observedGeneration: 2
